services:
  - type: web
    name: auth-spring-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:mem:testdb
      - key: CORS_ALLOWED_ORIGINS
        value: https://auth-template-phi.vercel.app,http://localhost:3000
