spring:
  application:
    name: auth-spring-api
  
  main:
    allow-circular-references: true
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: false  # Disable H2 console in production
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false  # Disable SQL logging in production
    properties:
      hibernate:
        format_sql: false

server:
  port: ${PORT:8080}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-fallback-secret-key}
  
# Session Configuration
session:
  lifetime: 120  # 2 minutes

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

logging:
  level:
    com.example.authapi: INFO
    org.springframework.security: WARN
    root: INFO
