name: Deploy to Render

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  JAVA_VERSION: '21'
  MAVEN_OPTS: -Dmaven.repo.local=~/.m2/repository

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
        
    - name: Run tests
      run: mvn clean test
      
    - name: Build application
      run: mvn clean compile package -DskipTests
      
    - name: Test Docker build
      run: |
        docker build -t auth-spring-api:test .
        echo "Docker build successful"

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Trigger Render Deploy
      run: |
        curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" \
          -H "Content-Type: application/json" \
          -d '{"ref": "${{ github.sha }}"}'
        
    - name: Deployment Triggered
      run: |
        echo "🚀 Deployment to Render has been triggered!"
        echo "Your application will be deployed from commit: ${{ github.sha }}"
        echo "Check your Render dashboard for deployment progress."
